### ISSUE TITLE
Formatting and un-formatting several times leads to inconsistent undo behavior

### ISSUE THREAD

**Issue by jmartinesp** [matrix-org/matrix-rich-text-editor#276]
Having:

 ```
let mut model = cm("{asd}|");
model.bold();
model.bold();
model.bold();
model.bold();
model.undo();
model.undo();
model.undo();
model.undo();
```

The several undo should render the text as bold half of the time. However, the rendered text is always plain text.

Can be reproduced in both Web and Android, so it seems to be a Rust issue.

**Comment by langleyd** [comment]
I tested this and it is now fixed.
