### ISSUE TITLE
Lists: deleteSurroundingText tries to delete the whole composition on a list item

### ISSUE THREAD

**Issue by jmartinesp** [matrix-org/matrix-rich-text-editor#278]
Given:

![image](https://user-images.githubusercontent.com/480955/200897835-b8716d98-1493-4c8d-9955-c71277cffe36.png)

If I try to delete the 1st character with a backspace press in any list item, `InterceptInputConnection.deleteSurroundingText(beforeLength: Int, afterLength: Int)` will be called by the OS with beforeLength being 1 (the character before the selection) and afterLength being the length of the rest of the word (4 in this case), so effectively the OS is telling us to delete the whole word for some reason. 

This is not what should happen and we need to either investigate why this is happening and fix it or replace the current implementation of that method with one that just deletes whatever the current selection is, although this might lead to some other side effects in unknown conditions.

**Comment by langleyd** [comment]
Tested on the latest and this works now, probably fixed during the paragraphs/lists re-work.
