### ISSUE TITLE
Highlighting text then clicking list should make the whole paragraph a list item

### ISSUE THREAD

**Issue by andybalaam** [matrix-org/matrix-rich-text-editor#282]
Confirmed in other rich text editors:

```
let mut model = cm("before <em>{italic}|</em> after");
model.create_unordered_list();
assert_eq!(tx(&model), "<ul><li>before <em>{italic}| after</em></li></ul>");
```

Note: this works as expected if you don’t have the italic part already.

The list should operate on the whole paragraph, which I think means expanding to cover all non-structural nodes before applying

**Comment by aringenbach** [comment]
https://github.com/matrix-org/matrix-rich-text-editor/pull/399
