### ISSUE TITLE
Web: after choosing a spell-check suggestion, the wrong spelling re-appears when I type

### ISSUE THREAD

**Issue by andybalaam** [matrix-org/matrix-rich-text-editor#286]
Mis-spell a word (in Web).
Choose the correct suggested spelling.
Type some more characters.

Observe that your wrong spelling re-appears.

**Comment by alunturner** [comment]
Testing this on web, v1.4.0 and this is no longer an issue - closing to tidy up some of our issue admin on this repo. Also tested on nightly for element web and it's fine there too.

https://user-images.githubusercontent.com/56027671/228847941-7925ecf1-b02e-4a3d-ae3d-0e5954295912.mov
