### ISSUE TITLE
[Android] Design fixes for the full screen mode and mic icon

### ISSUE THREAD

**Issue by jmartinesp** [matrix-org/matrix-rich-text-editor#328]
- [ ] Center the microphone icon vertically, since it seems to be a bit nearer to the bottom than expected.
- [ ] When the full screen mode is collapsed, don't hide the keyboard.

**Comment by jonnyandrew** [comment]
https://github.com/vector-im/element-android/pull/7658
https://github.com/vector-im/element-android/pull/7659
