### ISSUE TITLE
Rich Text Editor breaks the /rainbow command

### ISSUE THREAD

**Issue by ashughes1** [matrix-org/matrix-rich-text-editor#387]
Enabling the Rich Text Editor (RTE) stops /rainbow autocompletion and rainbowfying messages.

Steps:
1. With RTE disabled, start typing `/rainbow` (autocompletes to show the explanation of the rainbow command)
2. Continue typing so your message reads `/rainbow _message_` and press ENTER (message appears in the room coloured as a rainbow
3. Go to Labs and enable RTE
4. Start typing `/rainbow` followed by a message and press ENTER

Result:
* With RTE disabled the autocomplete explaining the rainbow command appears and any message that follows is formatted coloured as a rainbow.
* With RTE enabled the autocomplete explanation does not appear and what gets output is `/rainbow message` in plain, unformatted text

Tested this on Fedora Linux 37 with Element Desktop 1.11.16 installed via Flatpak from Flathub.org. I also replicated this on Element Android 1.5.10 on a Pixel 7 running GrapheneOS Tiramisu, Element iOS 1.9.13 on an iPhone 12 Mini running iOS 16.1.2 and staging.element.io on Firefox 107.0.1 on Fedora.

Here is a screenshot of the autocomplete with RTE disabled:
![Screenshot from 2022-12-08 15-06-19](https://user-images.githubusercontent.com/766595/206587090-2bd483f2-749f-42bf-948b-2a7faa0114ff.png)

Here is a screenshot of the message formatting, the first grouping of messages is with RTE enabled, the last message is with me entering `/rainbow message` with RTE disabled:
![Screenshot from 2022-12-08 15-18-28](https://user-images.githubusercontent.com/766595/206587170-600cd611-cee2-4e13-b5d2-5551780b659a.png)

I'd be happy to provide any other information that is useful.

**Comment by t3chguy** [comment]
Slash commands aren't functional at all in the RTE yet - see https://github.com/vector-im/element-web/issues/23880

**Comment by alunturner** [comment]
The rust side of this implementation was added in v1.2.0. Corresponding react-sdk work carried out in PRs:

- https://github.com/matrix-org/matrix-react-sdk/pull/10521
- https://github.com/matrix-org/matrix-react-sdk/pull/10560
- https://github.com/matrix-org/matrix-react-sdk/pull/10567

Opening a related issue to deal with the case where a user inserts a command inside a paragraph tag in the rich text editor. Issue here: https://github.com/matrix-org/matrix-rich-text-editor/issues/704
