### ISSUE TITLE
"deleteWordBackward" and "deleteWordForward" not supported

### ISSUE THREAD

**Issue by menturion** [matrix-org/matrix-rich-text-editor#397]
Type/enter "ctrl del" -> Console message: "Unknown input type: deleteWordBackward".

**Comment by menturion** [comment]
### Addendum ###

Same with `deleteWordForward`:  "Unknown input type: deleteWordForward".

**Comment by florianduros** [comment]
The `deleteWordBackward` and `deleteWordForward` is currently under development, it should be available soon.

**Comment by florianduros** [comment]
Duplicate of https://github.com/matrix-org/matrix-rich-text-editor/issues/321
