### ISSUE TITLE
[Lists] Crash after toggling list twice

### ISSUE THREAD

**Issue by jonnyandrew** [matrix-org/matrix-rich-text-editor#445]
## Steps to reproduce
- Checkout `921adc7`
- Toggle list on
- Toggle list off
- Type a character
- Backspace
- Toggle list on
- _Crash_

## Failing test
```rust
#[test]
fn toggle_list_then_type_text() {
    let mut model = cm("|");
    model.unordered_list();
    model.unordered_list();
    
    // State is now bad: "<ul></ul>~|"
    
    model.replace_text(utf16("A"));
    model.backspace();
    model.unordered_list(); // panic
}
```

## Screen recording
[list-crash.webm](https://user-images.githubusercontent.com/4940864/210563306-3b2bf5a1-8f9b-4f17-96d1-5034cdcf97e1.webm)

**Comment by alunturner** [comment]
I have also managed to reproduce this without any text input (ie by purely using the toggle) so it is possible that it is the toggling behaviour as opposed to the input that is causing this
