### ISSUE TITLE
[Code blocks] Code block is empty when created before new line

### ISSUE THREAD

**Issue by jonnyandrew** [matrix-org/matrix-rich-text-editor#455]
When a code block is created before a new line, text is not inserted to the right place.

## Steps to reproduce
- Create a new line
- Move the cursor to position 0
- Toggle code block on
- Type some text
- _Note text is created outside the code block_

## Failing test
```
#[test]
fn create_code_block_before_new_line() {
    let mut model = cm("|<br />");
    model.code_block();
    model.do_replace_text(utf16("hello"));
    model.enter();
    assert_eq!(tx(&model), "<pre>~hello<br />|</pre><br />");
    // actual: "<pre>~</pre>hello<br />|<br />"
}
```

## Screenshot
Note the model after the example in this video is:
```
<pre>~</pre>text is outside code block<br />and this is too|<br /><br />
```
[code-block-bug.webm](https://user-images.githubusercontent.com/4940864/210976325-32486583-b419-4c54-a923-e998f2d60419.webm)

**Comment by langleyd** [comment]
Tested and this is now fixed, likely as a part of the paragraphs rework.
