### ISSUE TITLE
[Code blocks] Lines are swapped after applying code block

### ISSUE THREAD

**Issue by jonnyandrew** [matrix-org/matrix-rich-text-editor#458]
## Steps to reproduce
- Type four lines of text
- Place the cursor at the end of the second line
- Toggle code block on
- _Note lines two and three are swapped_

## Failing test

    #[test]
    fn code_block_preserves_line_order() {
        let mut model = cm("A<br />B|<br />C<br />D");
        model.code_block();
        assert_eq!(tx(&model), "A<br /><pre>~B|</pre><br />C<br />D");
        // actual: "A<br />C<pre>~|B</pre><br />D"
    }

## Screen recording
[code-block-bug.webm](https://user-images.githubusercontent.com/4940864/211003901-e6781427-a882-433a-96ff-5b7dd7981f9a.webm)

**Comment by jmartinesp** [comment]
This should have been fixed by #505.
