### ISSUE TITLE
[Code blocks] [Quotes] Enter does not appear to move cursor to new line

### ISSUE THREAD

**Issue by alunturner** [matrix-org/matrix-rich-text-editor#491]
Seen in the [example app](https://matrix-org.github.io/matrix-rich-text-editor/ ) on 17 Jan.

**Steps to reproduce:**

- Start a code block 
- enter some text
- press enter
- note cursor appears to still be on same line
- start typing
- new text appears on a new line
This can be seen in the video below:

https://user-images.githubusercontent.com/56027671/212918729-9770bb13-2e9c-4208-87be-9df8c9fe10c3.mov

**Expected behaviour:**

- pressing enter moves the cursor to a new line and this can be seen by the user

**Notes:**

- I'm not sure if this is purely a web issue, but I think it could be so have labelled it as such
- This bug is a bit annoying combined with our decision to make two consecutive presses of `Enter` exit the code block, as there's no visual indication of the first press
- Same behaviour can be seen in Quotes

**Comment by alunturner** [comment]
This will be fixed by paragraph branch integration

**Comment by langleyd** [comment]
This is fixed now
