### ISSUE TITLE
[Code blocks] Inserting a code block can insert an additional linebreak

### ISSUE THREAD

**Issue by alunturner** [matrix-org/matrix-rich-text-editor#492]
Seen in the [example app](https://matrix-org.github.io/matrix-rich-text-editor/ ) on 17 Jan.

**Steps to reproduce:**

- write text on three separate lines
- highlight the middle line
- select code block
- note the appearance of another linebreak above the codeblock

https://user-images.githubusercontent.com/56027671/212920473-0f2d1d25-5ba8-445e-be38-192531e0b551.mov

**Expected behaviour:**

- inserting a code block in this way should only add the code block and not the extra linebreak

**Notes:**

- Looking at the video I actually wonder if it's just moving the second linebreak above the pre tag, so this might be an ordering issue as opposed to unexpectedly adding an element

**Comment by langleyd** [comment]
Tested and this is fixed now.
