### ISSUE TITLE
[Quotes] Linebreak not behaving as expected on exiting quote

### ISSUE THREAD

**Issue by alunturner** [matrix-org/matrix-rich-text-editor#499]
Seen in the [example app](https://matrix-org.github.io/matrix-rich-text-editor/) on 18 Jan.

**Steps to reproduce:**

- write some text (perhaps not necessary)
- click the quote button
- write some text
- press enter (note same issue as code blocks where cursor does not appear to move, raised in issue #491)
- note that linebreak appears inside the `blockquote` tag
- press enter again to stop editing the quote
- cursor moves outside the codeblock (good) but linebreak moves from inside the blockquote to the containing element

Uploading Screen Recording 2023-01-18 at 15.56.49.mov…

**Expected behaviour:**

- On second press of the enter key I think that the blockquote should have the final `br` node removed
- The cursor is then placed after the blockquote

**Comment by langleyd** [comment]
Tested and no longer an issue. We don't use line breaks but paragraphs now and a paragraph is correctly started after the quote.
