### ISSUE TITLE
Clicking `Quote` on a message in the timeline does not work as expected

### ISSUE THREAD

**Issue by alunturner** [matrix-org/matrix-rich-text-editor#503]
Seen in the element web on 19 Jan.

**Steps to reproduce:**

- with the current text editor, highlight a message in the timeline, click the three dots in the top corner, then click `Quote` on the menu that appears
- the composer will have the message, translated into markdown, inserted into it
- switch to the rich text editor
- repeat the first step to click on `Quote` on a message in the timeline
- nothing appears in the composer

**Expected behaviour:**

- as a guess, I'd say that the rich text editor should probably display the quoted message inside a `<blockquote>` tag, similarly to the current behaviour (but not in markdown)

**Comment by jonnyandrew** [comment]
Closing as it's not clear whether the problem lies in this project or Element Web. There is now an issue open against Element Web where the problem was discovered: https://github.com/vector-im/element-web/issues/26296

Please reopen if it turns out something can be done here to fix.
