### ISSUE TITLE
Ctrl+Backspace deletes everything instead of just one word

### ISSUE THREAD

**Issue by frebib** [matrix-org/matrix-rich-text-editor#603]
Almost every text field in every software ever supports Ctrl+Backspace to delete one word (except some, looking at you Microsoft 👀). In the Rich Text editor in Element Desktop (web) (nightly) it seems to delete multiple words, even when there is no formatting in the text field
![Peek 2023-03-04 16-07](https://user-images.githubusercontent.com/775104/222916479-f6ac7e2f-9b87-4dfd-bd51-4d5d03e71d2b.gif)

Element Web (without the RTE lab turned on) deletes one word (word char delimited) with Ctrl+Backspace
![Peek 2023-03-04 16-10](https://user-images.githubusercontent.com/775104/222916580-70a47923-573a-463c-ab50-5ba52ddb6f4b.gif)

**Comment by alunturner** [comment]
I've just had a look at this - error lies in event.ts > `getInputFromKeyDown`, it's using ctrl or meta as the modifier and this results in it firing the "deleteSoftLineBackward" event which results in this behaviour

**Comment by jonnyandrew** [comment]
Fixed by matrix-org/matrix-rich-text-editor#751
