### ISSUE TITLE
Typing a new line after an emoji causes panic

### ISSUE THREAD

**Issue by alunturner** [matrix-org/matrix-rich-text-editor#644]
## Steps to reproduce
- go to element web and copy some emojis
- open the example app and paste the emojis
- press shift + enter to insert a line break
- check the console, observe the selection covering the whole string of emojis

### Video

https://user-images.githubusercontent.com/56027671/228888092-71c677b9-a4d1-4300-a732-2e79816461e1.mov

Expected behaviour
- no panic

Notes
- In the example trying to insert a line break after the first or second emoji works, after the third or fourth it panics
- Actually a bit more testing suggests that it's once you get past halfway in a consecutive run of emojis and try to insert a line break, that's when it panics
- The point above suggests to me that we might actually be having a counting issue with the length of the emojis somewhere, perhaps when doing a calculation when splitting the string into paragraphs

**Comment by jonnyandrew** [comment]
This appears to be a bug in the rust model:

## Failing test
```rust
#[test]
fn enter_after_emoji() {
    let mut model = cm("🤗|");
    model.enter();
}
```

**Comment by jonnyandrew** [comment]
- Causes https://github.com/vector-im/element-x-android/issues/1394
