### ISSUE TITLE
 rich text editor remember draft?

### ISSUE THREAD

**Issue by Thatoo** [matrix-org/matrix-rich-text-editor#650]
Your use case
What would you like to do?

Before RTE, Element was remembering draft of unsent message when we were changing to an other room and coming back. I'd like RTE to be able to do the same.
Why would you like to do it?

Using RTE, if I'm composing a message and I need to look for some information in an other room, if I don't think I should copy/paste my draft before leaving the room, when I come back, I have to rewrite all the message as the draft has vanished
How would you like to achieve it?

RTE should remember drafts of last unsent message in each room.

**Comment by t3chguy** [comment]
Might be nice to sync drafts between clients too!

**Comment by aringenbach** [comment]
Thanks for your report @Thatoo 

This library doesn't save any data that is typed (and it will probably never will, as its designed to be pure text processing - not to mention the security issues if it starts saving pairs of text and room information), but it does provide tools like `set_content_from_html` and `set_content_from_markdown` to the hosting application. 
It's up to the application, so Element in your case, to save the partial messages and restore them in a new instance of the Rich Text Editor.

**Comment by Thatoo** [comment]
Good.
In this case, could you reopen my original request https://github.com/vector-im/element-web/issues/25135#event-9034892627 ? And then we could close this request.
