### ISSUE TITLE
Add ability to output html and markdown formatted specifically for message content

### ISSUE THREAD

**Issue by alunturner** [matrix-org/matrix-rich-text-editor#679]
We have discussed on multiple occasions the benefits of creating and exposing a function that would allow us to output the html and markdown from the Rust model but _specifically_ for sending as message content. 

This issue records some of the things we think it should do, noting that some of these approaches may change depending on other design decisions:
**HTML output (to attach to formatted body)**
- remove empty `<p>` tags from the message (ie `<p>&nbsp;</p>`), which we currently use to represent an empty paragraph that the user may potentially put their cursor inside whilst editing https://github.com/matrix-org/matrix-rich-text-editor/pull/686
- strip any attributes from `<a>` tags that aren't href (to remove custom attributes used for display) https://github.com/matrix-org/matrix-rich-text-editor/pull/716
- replace `at-room` mentions with the plain text `@room` as this is what the timeline seems to expect https://github.com/matrix-org/matrix-rich-text-editor/pull/716
- replace the inner text of a room mention link with the mxId (think this is what the spec dictates, should this be the same for users?)

**Markdown output (to attach to body)**
- replace mention link representations with just the mxId, prefixed with @ or # as appropriate

There may be more work required, but this is what we've come across so far.

```[tasklist]
### Tasks
- [x] https://github.com/matrix-org/matrix-rich-text-editor/pull/686
- [ ] Expose new get_content_as_message_html() function from platform libraries
```

**Comment by jonnyandrew** [comment]
> we will add a function that outputs the Rust state as markdown that meets the Matrix spec

Would we need two different ways to get markdown output if mentions will not be represented as links in the Rust model?

**Comment by alunturner** [comment]
> > we will add a function that outputs the Rust state as markdown that meets the Matrix spec
> 
> Would we need two different ways to get markdown output if mentions will not be represented as links in the Rust model?

Hmm. It's an interesting question. Initially I thought so, but perhaps not. It wouldn't affect web implementation I don't think  but I'd be concerned about whether it would affect iOS at all.
