### ISSUE TITLE
Pasting images from clipboard

### ISSUE THREAD

**Issue by hanthor** [matrix-org/matrix-rich-text-editor#696]
Only able to paste images when the composer is unselected, but if the composer is active, pasting does nothing

**Comment by alunturner** [comment]
Hello! This has been addressed in PRs targeting this repo and the matrix-react-sdk repo. Relevant PRs:

- [PR to add `beforeinput` listener here](https://github.com/matrix-org/matrix-rich-text-editor/pull/710)
- [PR to use that in the rich text editor rich text mode
](https://github.com/matrix-org/matrix-react-sdk/pull/11049)
[- PR to use that in the plain text mode](https://github.com/matrix-org/matrix-react-sdk/pull/11056)
