### ISSUE TITLE
Automatically describe mention type in HTML

### ISSUE THREAD

**Issue by jonnyandrew** [matrix-org/matrix-rich-text-editor#709]
## Problem
To help with rendering of mentions, web clients attach attributes to the HTML link tag `<a>` to identify the link as a mention and keep track of it's type. Now that this library is responsible for parsing Matrix mentions, this is no longer necessary.

## Solution 1

- #714 

## Solution 2

Depends on
- https://github.com/matrix-org/matrix-rich-text-editor/issues/692
- which is partially implemented in https://github.com/matrix-org/matrix-rich-text-editor/pull/695

Given some mentions are parsed by the library into a mention nodes:

```html
<a href="https://matrix.to/#/@test:example.org">test</a>
<a href="https://matrix.to/#/#test:example.org">#test:example.org</a>
```

When I get the internal content as HTML (`get_content_as_html()`), it should have the `data-mention-type` attribute with an appropriate value (`room` or `user`):

```html
<a href="https://matrix.to/#/@test:example.org" data-mention-type="user">test</a>
<a href="https://matrix.to/#/#test:example.org" data-mention-type="room">#test:example.org</a>
```

Note that `get_content_as_message_html()` should **not** return this attribute.

**Comment by alunturner** [comment]
Addressed in release 2.3.0
