### ISSUE TITLE
With plain text mode selected, opening a thread should open the composer in plain text mode

### ISSUE THREAD

**Issue by alunturner** [matrix-org/matrix-rich-text-editor#715]
When using the rich text editor, if you switch the "main" composer (ie the one beneath the timeline) to plain text mode, then open a thread, the "new" composer (ie the one in the thread panel) opens in "rich" mode. See screenshot below.

<img width="1627" alt="Element__2____Alun_Turner" src="https://github.com/matrix-org/matrix-rich-text-editor/assets/56027671/9f4dec55-34f9-4a67-ba23-df939d51a77c">

Better behaviour would be for the "new" composer to open in the same setting as the "main" composer

**Comment by jonnyandrew** [comment]
Closing as we can't fix this issue from the RTE itself. If you're still seeing the problem, please can you reopen it against [vector-im/element-web](https://github.com/vector-im/element-web).
