### ISSUE TITLE
Replace Uniffi fork when a new version lands

### ISSUE THREAD

**Issue by aringenbach** [matrix-org/matrix-rich-text-editor#783]
Since moving to a dynamic Swift library (https://github.com/matrix-org/matrix-rich-text-editor/pull/782), symbols won't clash anymore. So the only reason to keep our fork of `uniffi-rs` is a library mode build fix around crate types that is unreleased yet, see https://github.com/matrix-org/matrix-rich-text-editor/pull/768.

The required fix should be available in uniffi version `0.24.4` / `0.25.0`. We can then replace the configuration for the fork at https://github.com/matrix-org/matrix-rich-text-editor/blob/d76a9f861e489191cace786ea7a0536a938688d3/Cargo.toml#L19 with the standard new version of uniffi.

**Comment by aringenbach** [comment]
Currently blocked because of: https://github.com/matrix-org/matrix-rich-text-editor/pull/786

Replacing the Uniffi fork will only be possible when symbols issues are fixed: https://github.com/mozilla/uniffi-rs/issues/1670

**Comment by jonnyandrew** [comment]
Is this unblocked now that https://github.com/mozilla/uniffi-rs/issues/1670 is resolved by https://github.com/mozilla/uniffi-rs/pull/1735 ?

**Comment by aringenbach** [comment]
Seems like there was no release yet, we could though try to use a commit from the main branch.
But yeah from what I'm reading it seems that there shouldn't be anything preventing us from going back to the official repository (as long as both the fix for library path & this one are part of whatever version we are using)
