### ISSUE TITLE
Creating a list only includes the formatted part in the list item

### ISSUE THREAD

**Issue by callumu** [matrix-org/matrix-rich-text-editor#90]
**Describe the bug**
When making an unordered list from text that is formatted in two different ways, the list will be created from the part of the text that has first been formatted with the second part of the text appearing on a separate line below. For example, this text **wqw**_eaedaw_ would become:

- **wqw**
 _eaedaw_

**Expected behavior**
The entirety of the text forming a list

**Test Case**
let mut model = cm("sadsaww{daswdaswd}|");
model.italic();
model.select(Location::from(7), Location::from(7));
model.underline();
model.select(Location::from(7), Location::from(7));
model.underline();
model.underline();
model.italic();
model.select(Location::from(7), Location::from(7));
model.strike_through();
model.select(Location::from(0), Location::from(7));
model.unordered_list();
assert_eq!(tx(&model), "<ul><li>{sadsaww}|</li></ul><del></del><em></em><u></u><u></u><u></u><em>daswdaswd</em>");

**Comment by aringenbach** [comment]
https://github.com/matrix-org/matrix-rich-text-editor/pull/399
